name: Run gradle build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: qupath/actions/.github/workflows/gradle.yml@main
    with:
      platform: ${{ matrix.platform }}
      build-tool: ${{ matrix.platform == 'ubuntu-latest' && 'xfvb-run ./gradlew' || './gradlew' }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
