# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.2

      - name: Execute Gradle build (Ubuntu)
        run: xvfb-run ./gradlew build -P toolchain=17
        if: matrix.os == 'ubuntu-latest'

      - name: Execute Gradle build (Windows and MacOS)
        run: ./gradlew build -P toolchain=17
        if: matrix.os == 'windows-latest' || matrix.os == 'macos-latest'

      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
