# This workflow will build a Java project with Gradle, then create an image with jpackage
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build packages with jpackage

on: [workflow_dispatch]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: jpackage -P git-commit=true -P package=installer mergedJavadoc
      - uses: actions/upload-artifact@v3
        with:
          name: jpackage ${{ matrix.platform }}
          path: build/dist
          retention-days: 1
      - uses: actions/upload-artifact@v3
        with:
          name: javadoc ${{ matrix.platform }}
          path: build/docs/javadoc
          retention-days: 1
